/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ClientRouteImport } from './routes/client'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientIndexRouteImport } from './routes/client.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ClientOrdersRouteImport } from './routes/client.orders'
import { Route as ClientNewOrderRouteImport } from './routes/client.new-order'
import { Route as ClientCatalogRouteImport } from './routes/client.catalog'
import { Route as ClientAskRouteImport } from './routes/client.ask'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminPricingRouteImport } from './routes/admin.pricing'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminMarginsRouteImport } from './routes/admin.margins'
import { Route as AdminExportRouteImport } from './routes/admin.export'
import { Route as AdminCopilotRouteImport } from './routes/admin.copilot'
import { Route as AdminContainerRouteImport } from './routes/admin.container'
import { Route as AdminAgentsRouteImport } from './routes/admin.agents'
import { Route as AdminOrderDetailsOrderIdRouteImport } from './routes/admin.order-details.$orderId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRoute = ClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientIndexRoute = ClientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ClientOrdersRoute = ClientOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => ClientRoute,
} as any)
const ClientNewOrderRoute = ClientNewOrderRouteImport.update({
  id: '/new-order',
  path: '/new-order',
  getParentRoute: () => ClientRoute,
} as any)
const ClientCatalogRoute = ClientCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => ClientRoute,
} as any)
const ClientAskRoute = ClientAskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => ClientRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPricingRoute = AdminPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarginsRoute = AdminMarginsRouteImport.update({
  id: '/margins',
  path: '/margins',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExportRoute = AdminExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCopilotRoute = AdminCopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContainerRoute = AdminContainerRouteImport.update({
  id: '/container',
  path: '/container',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAgentsRoute = AdminAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrderDetailsOrderIdRoute =
  AdminOrderDetailsOrderIdRouteImport.update({
    id: '/order-details/$orderId',
    path: '/order-details/$orderId',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/client': typeof ClientRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/container': typeof AdminContainerRoute
  '/admin/copilot': typeof AdminCopilotRoute
  '/admin/export': typeof AdminExportRoute
  '/admin/margins': typeof AdminMarginsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/client/ask': typeof ClientAskRoute
  '/client/catalog': typeof ClientCatalogRoute
  '/client/new-order': typeof ClientNewOrderRoute
  '/client/orders': typeof ClientOrdersRoute
  '/admin/': typeof AdminIndexRoute
  '/client/': typeof ClientIndexRoute
  '/admin/order-details/$orderId': typeof AdminOrderDetailsOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/container': typeof AdminContainerRoute
  '/admin/copilot': typeof AdminCopilotRoute
  '/admin/export': typeof AdminExportRoute
  '/admin/margins': typeof AdminMarginsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/client/ask': typeof ClientAskRoute
  '/client/catalog': typeof ClientCatalogRoute
  '/client/new-order': typeof ClientNewOrderRoute
  '/client/orders': typeof ClientOrdersRoute
  '/admin': typeof AdminIndexRoute
  '/client': typeof ClientIndexRoute
  '/admin/order-details/$orderId': typeof AdminOrderDetailsOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/client': typeof ClientRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/container': typeof AdminContainerRoute
  '/admin/copilot': typeof AdminCopilotRoute
  '/admin/export': typeof AdminExportRoute
  '/admin/margins': typeof AdminMarginsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/client/ask': typeof ClientAskRoute
  '/client/catalog': typeof ClientCatalogRoute
  '/client/new-order': typeof ClientNewOrderRoute
  '/client/orders': typeof ClientOrdersRoute
  '/admin/': typeof AdminIndexRoute
  '/client/': typeof ClientIndexRoute
  '/admin/order-details/$orderId': typeof AdminOrderDetailsOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/client'
    | '/login'
    | '/admin/agents'
    | '/admin/container'
    | '/admin/copilot'
    | '/admin/export'
    | '/admin/margins'
    | '/admin/orders'
    | '/admin/pricing'
    | '/admin/settings'
    | '/admin/users'
    | '/client/ask'
    | '/client/catalog'
    | '/client/new-order'
    | '/client/orders'
    | '/admin/'
    | '/client/'
    | '/admin/order-details/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/agents'
    | '/admin/container'
    | '/admin/copilot'
    | '/admin/export'
    | '/admin/margins'
    | '/admin/orders'
    | '/admin/pricing'
    | '/admin/settings'
    | '/admin/users'
    | '/client/ask'
    | '/client/catalog'
    | '/client/new-order'
    | '/client/orders'
    | '/admin'
    | '/client'
    | '/admin/order-details/$orderId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/client'
    | '/login'
    | '/admin/agents'
    | '/admin/container'
    | '/admin/copilot'
    | '/admin/export'
    | '/admin/margins'
    | '/admin/orders'
    | '/admin/pricing'
    | '/admin/settings'
    | '/admin/users'
    | '/client/ask'
    | '/client/catalog'
    | '/client/new-order'
    | '/client/orders'
    | '/admin/'
    | '/client/'
    | '/admin/order-details/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ClientRoute: typeof ClientRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client': {
      id: '/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof ClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/': {
      id: '/client/'
      path: '/'
      fullPath: '/client/'
      preLoaderRoute: typeof ClientIndexRouteImport
      parentRoute: typeof ClientRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/client/orders': {
      id: '/client/orders'
      path: '/orders'
      fullPath: '/client/orders'
      preLoaderRoute: typeof ClientOrdersRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/new-order': {
      id: '/client/new-order'
      path: '/new-order'
      fullPath: '/client/new-order'
      preLoaderRoute: typeof ClientNewOrderRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/catalog': {
      id: '/client/catalog'
      path: '/catalog'
      fullPath: '/client/catalog'
      preLoaderRoute: typeof ClientCatalogRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/ask': {
      id: '/client/ask'
      path: '/ask'
      fullPath: '/client/ask'
      preLoaderRoute: typeof ClientAskRouteImport
      parentRoute: typeof ClientRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pricing': {
      id: '/admin/pricing'
      path: '/pricing'
      fullPath: '/admin/pricing'
      preLoaderRoute: typeof AdminPricingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/margins': {
      id: '/admin/margins'
      path: '/margins'
      fullPath: '/admin/margins'
      preLoaderRoute: typeof AdminMarginsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/export': {
      id: '/admin/export'
      path: '/export'
      fullPath: '/admin/export'
      preLoaderRoute: typeof AdminExportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/copilot': {
      id: '/admin/copilot'
      path: '/copilot'
      fullPath: '/admin/copilot'
      preLoaderRoute: typeof AdminCopilotRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/container': {
      id: '/admin/container'
      path: '/container'
      fullPath: '/admin/container'
      preLoaderRoute: typeof AdminContainerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/agents': {
      id: '/admin/agents'
      path: '/agents'
      fullPath: '/admin/agents'
      preLoaderRoute: typeof AdminAgentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/order-details/$orderId': {
      id: '/admin/order-details/$orderId'
      path: '/order-details/$orderId'
      fullPath: '/admin/order-details/$orderId'
      preLoaderRoute: typeof AdminOrderDetailsOrderIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAgentsRoute: typeof AdminAgentsRoute
  AdminContainerRoute: typeof AdminContainerRoute
  AdminCopilotRoute: typeof AdminCopilotRoute
  AdminExportRoute: typeof AdminExportRoute
  AdminMarginsRoute: typeof AdminMarginsRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPricingRoute: typeof AdminPricingRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminOrderDetailsOrderIdRoute: typeof AdminOrderDetailsOrderIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAgentsRoute: AdminAgentsRoute,
  AdminContainerRoute: AdminContainerRoute,
  AdminCopilotRoute: AdminCopilotRoute,
  AdminExportRoute: AdminExportRoute,
  AdminMarginsRoute: AdminMarginsRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPricingRoute: AdminPricingRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminOrderDetailsOrderIdRoute: AdminOrderDetailsOrderIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ClientRouteChildren {
  ClientAskRoute: typeof ClientAskRoute
  ClientCatalogRoute: typeof ClientCatalogRoute
  ClientNewOrderRoute: typeof ClientNewOrderRoute
  ClientOrdersRoute: typeof ClientOrdersRoute
  ClientIndexRoute: typeof ClientIndexRoute
}

const ClientRouteChildren: ClientRouteChildren = {
  ClientAskRoute: ClientAskRoute,
  ClientCatalogRoute: ClientCatalogRoute,
  ClientNewOrderRoute: ClientNewOrderRoute,
  ClientOrdersRoute: ClientOrdersRoute,
  ClientIndexRoute: ClientIndexRoute,
}

const ClientRouteWithChildren =
  ClientRoute._addFileChildren(ClientRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ClientRoute: ClientRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
