/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ClientRouteImport } from './routes/client'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientIndexRouteImport } from './routes/client.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ClientOrdersRouteImport } from './routes/client.orders'
import { Route as ClientNewOrderRouteImport } from './routes/client.new-order'
import { Route as ClientCatalogRouteImport } from './routes/client.catalog'
import { Route as ClientAskRouteImport } from './routes/client.ask'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminPricingRouteImport } from './routes/admin.pricing'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminMarginsRouteImport } from './routes/admin.margins'
import { Route as AdminKnowledgeRouteImport } from './routes/admin.knowledge'
import { Route as AdminExportRouteImport } from './routes/admin.export'
import { Route as AdminCopilotRouteImport } from './routes/admin.copilot'
import { Route as AdminContainerRouteImport } from './routes/admin.container'
import { Route as AdminAgentsRouteImport } from './routes/admin.agents'
import { Route as ClientDevisIndexRouteImport } from './routes/client.devis.index'
import { Route as AdminProduitsIndexRouteImport } from './routes/admin.produits.index'
import { Route as AdminDevisIndexRouteImport } from './routes/admin.devis.index'
import { Route as AdminContainerIndexRouteImport } from './routes/admin.container.index'
import { Route as AdminCommandesIndexRouteImport } from './routes/admin.commandes.index'
import { Route as AdminClientsIndexRouteImport } from './routes/admin.clients.index'
import { Route as AdminAgentsIndexRouteImport } from './routes/admin.agents.index'
import { Route as ClientDevisQuoteIdRouteImport } from './routes/client.devis.$quoteId'
import { Route as ClientCommandesReferenceRouteImport } from './routes/client.commandes.$reference'
import { Route as AdminProduitsNouveauRouteImport } from './routes/admin.produits.nouveau'
import { Route as AdminProduitsImportRouteImport } from './routes/admin.produits.import'
import { Route as AdminProduitsRefRouteImport } from './routes/admin.produits.$ref'
import { Route as AdminPricingWorkflowOrderIdRouteImport } from './routes/admin.pricing-workflow.$orderId'
import { Route as AdminOrderDetailsOrderIdRouteImport } from './routes/admin.order-details.$orderId'
import { Route as AdminDevisQuoteIdRouteImport } from './routes/admin.devis.$quoteId'
import { Route as AdminContainerOrderIdRouteImport } from './routes/admin.container.$orderId'
import { Route as AdminCommandesReferenceRouteImport } from './routes/admin.commandes.$reference'
import { Route as AdminClientsClientIdRouteImport } from './routes/admin.clients.$clientId'
import { Route as AdminAgentsPricingRouteImport } from './routes/admin.agents.pricing'
import { Route as AdminAgentsMargeRouteImport } from './routes/admin.agents.marge'
import { Route as AdminAgentsExportRouteImport } from './routes/admin.agents.export'
import { Route as AdminAgentsContainerOptimizerRouteImport } from './routes/admin.agents.container-optimizer'
import { Route as AdminAgentsAgentIdRouteImport } from './routes/admin.agents.$agentId'
import { Route as AdminDevisGenererReferenceRouteImport } from './routes/admin.devis.generer.$reference'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRoute = ClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientIndexRoute = ClientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ClientOrdersRoute = ClientOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => ClientRoute,
} as any)
const ClientNewOrderRoute = ClientNewOrderRouteImport.update({
  id: '/new-order',
  path: '/new-order',
  getParentRoute: () => ClientRoute,
} as any)
const ClientCatalogRoute = ClientCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => ClientRoute,
} as any)
const ClientAskRoute = ClientAskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => ClientRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPricingRoute = AdminPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarginsRoute = AdminMarginsRouteImport.update({
  id: '/margins',
  path: '/margins',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKnowledgeRoute = AdminKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExportRoute = AdminExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCopilotRoute = AdminCopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContainerRoute = AdminContainerRouteImport.update({
  id: '/container',
  path: '/container',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAgentsRoute = AdminAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AdminRoute,
} as any)
const ClientDevisIndexRoute = ClientDevisIndexRouteImport.update({
  id: '/devis/',
  path: '/devis/',
  getParentRoute: () => ClientRoute,
} as any)
const AdminProduitsIndexRoute = AdminProduitsIndexRouteImport.update({
  id: '/produits/',
  path: '/produits/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDevisIndexRoute = AdminDevisIndexRouteImport.update({
  id: '/devis/',
  path: '/devis/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContainerIndexRoute = AdminContainerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminContainerRoute,
} as any)
const AdminCommandesIndexRoute = AdminCommandesIndexRouteImport.update({
  id: '/commandes/',
  path: '/commandes/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientsIndexRoute = AdminClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAgentsIndexRoute = AdminAgentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAgentsRoute,
} as any)
const ClientDevisQuoteIdRoute = ClientDevisQuoteIdRouteImport.update({
  id: '/devis/$quoteId',
  path: '/devis/$quoteId',
  getParentRoute: () => ClientRoute,
} as any)
const ClientCommandesReferenceRoute =
  ClientCommandesReferenceRouteImport.update({
    id: '/commandes/$reference',
    path: '/commandes/$reference',
    getParentRoute: () => ClientRoute,
  } as any)
const AdminProduitsNouveauRoute = AdminProduitsNouveauRouteImport.update({
  id: '/produits/nouveau',
  path: '/produits/nouveau',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProduitsImportRoute = AdminProduitsImportRouteImport.update({
  id: '/produits/import',
  path: '/produits/import',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProduitsRefRoute = AdminProduitsRefRouteImport.update({
  id: '/produits/$ref',
  path: '/produits/$ref',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPricingWorkflowOrderIdRoute =
  AdminPricingWorkflowOrderIdRouteImport.update({
    id: '/pricing-workflow/$orderId',
    path: '/pricing-workflow/$orderId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminOrderDetailsOrderIdRoute =
  AdminOrderDetailsOrderIdRouteImport.update({
    id: '/order-details/$orderId',
    path: '/order-details/$orderId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminDevisQuoteIdRoute = AdminDevisQuoteIdRouteImport.update({
  id: '/devis/$quoteId',
  path: '/devis/$quoteId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContainerOrderIdRoute = AdminContainerOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => AdminContainerRoute,
} as any)
const AdminCommandesReferenceRoute = AdminCommandesReferenceRouteImport.update({
  id: '/commandes/$reference',
  path: '/commandes/$reference',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientsClientIdRoute = AdminClientsClientIdRouteImport.update({
  id: '/clients/$clientId',
  path: '/clients/$clientId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAgentsPricingRoute = AdminAgentsPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AdminAgentsRoute,
} as any)
const AdminAgentsMargeRoute = AdminAgentsMargeRouteImport.update({
  id: '/marge',
  path: '/marge',
  getParentRoute: () => AdminAgentsRoute,
} as any)
const AdminAgentsExportRoute = AdminAgentsExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => AdminAgentsRoute,
} as any)
const AdminAgentsContainerOptimizerRoute =
  AdminAgentsContainerOptimizerRouteImport.update({
    id: '/container-optimizer',
    path: '/container-optimizer',
    getParentRoute: () => AdminAgentsRoute,
  } as any)
const AdminAgentsAgentIdRoute = AdminAgentsAgentIdRouteImport.update({
  id: '/$agentId',
  path: '/$agentId',
  getParentRoute: () => AdminAgentsRoute,
} as any)
const AdminDevisGenererReferenceRoute =
  AdminDevisGenererReferenceRouteImport.update({
    id: '/devis/generer/$reference',
    path: '/devis/generer/$reference',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/client': typeof ClientRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/agents': typeof AdminAgentsRouteWithChildren
  '/admin/container': typeof AdminContainerRouteWithChildren
  '/admin/copilot': typeof AdminCopilotRoute
  '/admin/export': typeof AdminExportRoute
  '/admin/knowledge': typeof AdminKnowledgeRoute
  '/admin/margins': typeof AdminMarginsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/client/ask': typeof ClientAskRoute
  '/client/catalog': typeof ClientCatalogRoute
  '/client/new-order': typeof ClientNewOrderRoute
  '/client/orders': typeof ClientOrdersRoute
  '/admin/': typeof AdminIndexRoute
  '/client/': typeof ClientIndexRoute
  '/admin/agents/$agentId': typeof AdminAgentsAgentIdRoute
  '/admin/agents/container-optimizer': typeof AdminAgentsContainerOptimizerRoute
  '/admin/agents/export': typeof AdminAgentsExportRoute
  '/admin/agents/marge': typeof AdminAgentsMargeRoute
  '/admin/agents/pricing': typeof AdminAgentsPricingRoute
  '/admin/clients/$clientId': typeof AdminClientsClientIdRoute
  '/admin/commandes/$reference': typeof AdminCommandesReferenceRoute
  '/admin/container/$orderId': typeof AdminContainerOrderIdRoute
  '/admin/devis/$quoteId': typeof AdminDevisQuoteIdRoute
  '/admin/order-details/$orderId': typeof AdminOrderDetailsOrderIdRoute
  '/admin/pricing-workflow/$orderId': typeof AdminPricingWorkflowOrderIdRoute
  '/admin/produits/$ref': typeof AdminProduitsRefRoute
  '/admin/produits/import': typeof AdminProduitsImportRoute
  '/admin/produits/nouveau': typeof AdminProduitsNouveauRoute
  '/client/commandes/$reference': typeof ClientCommandesReferenceRoute
  '/client/devis/$quoteId': typeof ClientDevisQuoteIdRoute
  '/admin/agents/': typeof AdminAgentsIndexRoute
  '/admin/clients/': typeof AdminClientsIndexRoute
  '/admin/commandes/': typeof AdminCommandesIndexRoute
  '/admin/container/': typeof AdminContainerIndexRoute
  '/admin/devis/': typeof AdminDevisIndexRoute
  '/admin/produits/': typeof AdminProduitsIndexRoute
  '/client/devis/': typeof ClientDevisIndexRoute
  '/admin/devis/generer/$reference': typeof AdminDevisGenererReferenceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/copilot': typeof AdminCopilotRoute
  '/admin/export': typeof AdminExportRoute
  '/admin/knowledge': typeof AdminKnowledgeRoute
  '/admin/margins': typeof AdminMarginsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/client/ask': typeof ClientAskRoute
  '/client/catalog': typeof ClientCatalogRoute
  '/client/new-order': typeof ClientNewOrderRoute
  '/client/orders': typeof ClientOrdersRoute
  '/admin': typeof AdminIndexRoute
  '/client': typeof ClientIndexRoute
  '/admin/agents/$agentId': typeof AdminAgentsAgentIdRoute
  '/admin/agents/container-optimizer': typeof AdminAgentsContainerOptimizerRoute
  '/admin/agents/export': typeof AdminAgentsExportRoute
  '/admin/agents/marge': typeof AdminAgentsMargeRoute
  '/admin/agents/pricing': typeof AdminAgentsPricingRoute
  '/admin/clients/$clientId': typeof AdminClientsClientIdRoute
  '/admin/commandes/$reference': typeof AdminCommandesReferenceRoute
  '/admin/container/$orderId': typeof AdminContainerOrderIdRoute
  '/admin/devis/$quoteId': typeof AdminDevisQuoteIdRoute
  '/admin/order-details/$orderId': typeof AdminOrderDetailsOrderIdRoute
  '/admin/pricing-workflow/$orderId': typeof AdminPricingWorkflowOrderIdRoute
  '/admin/produits/$ref': typeof AdminProduitsRefRoute
  '/admin/produits/import': typeof AdminProduitsImportRoute
  '/admin/produits/nouveau': typeof AdminProduitsNouveauRoute
  '/client/commandes/$reference': typeof ClientCommandesReferenceRoute
  '/client/devis/$quoteId': typeof ClientDevisQuoteIdRoute
  '/admin/agents': typeof AdminAgentsIndexRoute
  '/admin/clients': typeof AdminClientsIndexRoute
  '/admin/commandes': typeof AdminCommandesIndexRoute
  '/admin/container': typeof AdminContainerIndexRoute
  '/admin/devis': typeof AdminDevisIndexRoute
  '/admin/produits': typeof AdminProduitsIndexRoute
  '/client/devis': typeof ClientDevisIndexRoute
  '/admin/devis/generer/$reference': typeof AdminDevisGenererReferenceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/client': typeof ClientRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/agents': typeof AdminAgentsRouteWithChildren
  '/admin/container': typeof AdminContainerRouteWithChildren
  '/admin/copilot': typeof AdminCopilotRoute
  '/admin/export': typeof AdminExportRoute
  '/admin/knowledge': typeof AdminKnowledgeRoute
  '/admin/margins': typeof AdminMarginsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/client/ask': typeof ClientAskRoute
  '/client/catalog': typeof ClientCatalogRoute
  '/client/new-order': typeof ClientNewOrderRoute
  '/client/orders': typeof ClientOrdersRoute
  '/admin/': typeof AdminIndexRoute
  '/client/': typeof ClientIndexRoute
  '/admin/agents/$agentId': typeof AdminAgentsAgentIdRoute
  '/admin/agents/container-optimizer': typeof AdminAgentsContainerOptimizerRoute
  '/admin/agents/export': typeof AdminAgentsExportRoute
  '/admin/agents/marge': typeof AdminAgentsMargeRoute
  '/admin/agents/pricing': typeof AdminAgentsPricingRoute
  '/admin/clients/$clientId': typeof AdminClientsClientIdRoute
  '/admin/commandes/$reference': typeof AdminCommandesReferenceRoute
  '/admin/container/$orderId': typeof AdminContainerOrderIdRoute
  '/admin/devis/$quoteId': typeof AdminDevisQuoteIdRoute
  '/admin/order-details/$orderId': typeof AdminOrderDetailsOrderIdRoute
  '/admin/pricing-workflow/$orderId': typeof AdminPricingWorkflowOrderIdRoute
  '/admin/produits/$ref': typeof AdminProduitsRefRoute
  '/admin/produits/import': typeof AdminProduitsImportRoute
  '/admin/produits/nouveau': typeof AdminProduitsNouveauRoute
  '/client/commandes/$reference': typeof ClientCommandesReferenceRoute
  '/client/devis/$quoteId': typeof ClientDevisQuoteIdRoute
  '/admin/agents/': typeof AdminAgentsIndexRoute
  '/admin/clients/': typeof AdminClientsIndexRoute
  '/admin/commandes/': typeof AdminCommandesIndexRoute
  '/admin/container/': typeof AdminContainerIndexRoute
  '/admin/devis/': typeof AdminDevisIndexRoute
  '/admin/produits/': typeof AdminProduitsIndexRoute
  '/client/devis/': typeof ClientDevisIndexRoute
  '/admin/devis/generer/$reference': typeof AdminDevisGenererReferenceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/client'
    | '/login'
    | '/admin/agents'
    | '/admin/container'
    | '/admin/copilot'
    | '/admin/export'
    | '/admin/knowledge'
    | '/admin/margins'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/pricing'
    | '/admin/settings'
    | '/admin/users'
    | '/client/ask'
    | '/client/catalog'
    | '/client/new-order'
    | '/client/orders'
    | '/admin/'
    | '/client/'
    | '/admin/agents/$agentId'
    | '/admin/agents/container-optimizer'
    | '/admin/agents/export'
    | '/admin/agents/marge'
    | '/admin/agents/pricing'
    | '/admin/clients/$clientId'
    | '/admin/commandes/$reference'
    | '/admin/container/$orderId'
    | '/admin/devis/$quoteId'
    | '/admin/order-details/$orderId'
    | '/admin/pricing-workflow/$orderId'
    | '/admin/produits/$ref'
    | '/admin/produits/import'
    | '/admin/produits/nouveau'
    | '/client/commandes/$reference'
    | '/client/devis/$quoteId'
    | '/admin/agents/'
    | '/admin/clients/'
    | '/admin/commandes/'
    | '/admin/container/'
    | '/admin/devis/'
    | '/admin/produits/'
    | '/client/devis/'
    | '/admin/devis/generer/$reference'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/copilot'
    | '/admin/export'
    | '/admin/knowledge'
    | '/admin/margins'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/pricing'
    | '/admin/settings'
    | '/admin/users'
    | '/client/ask'
    | '/client/catalog'
    | '/client/new-order'
    | '/client/orders'
    | '/admin'
    | '/client'
    | '/admin/agents/$agentId'
    | '/admin/agents/container-optimizer'
    | '/admin/agents/export'
    | '/admin/agents/marge'
    | '/admin/agents/pricing'
    | '/admin/clients/$clientId'
    | '/admin/commandes/$reference'
    | '/admin/container/$orderId'
    | '/admin/devis/$quoteId'
    | '/admin/order-details/$orderId'
    | '/admin/pricing-workflow/$orderId'
    | '/admin/produits/$ref'
    | '/admin/produits/import'
    | '/admin/produits/nouveau'
    | '/client/commandes/$reference'
    | '/client/devis/$quoteId'
    | '/admin/agents'
    | '/admin/clients'
    | '/admin/commandes'
    | '/admin/container'
    | '/admin/devis'
    | '/admin/produits'
    | '/client/devis'
    | '/admin/devis/generer/$reference'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/client'
    | '/login'
    | '/admin/agents'
    | '/admin/container'
    | '/admin/copilot'
    | '/admin/export'
    | '/admin/knowledge'
    | '/admin/margins'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/pricing'
    | '/admin/settings'
    | '/admin/users'
    | '/client/ask'
    | '/client/catalog'
    | '/client/new-order'
    | '/client/orders'
    | '/admin/'
    | '/client/'
    | '/admin/agents/$agentId'
    | '/admin/agents/container-optimizer'
    | '/admin/agents/export'
    | '/admin/agents/marge'
    | '/admin/agents/pricing'
    | '/admin/clients/$clientId'
    | '/admin/commandes/$reference'
    | '/admin/container/$orderId'
    | '/admin/devis/$quoteId'
    | '/admin/order-details/$orderId'
    | '/admin/pricing-workflow/$orderId'
    | '/admin/produits/$ref'
    | '/admin/produits/import'
    | '/admin/produits/nouveau'
    | '/client/commandes/$reference'
    | '/client/devis/$quoteId'
    | '/admin/agents/'
    | '/admin/clients/'
    | '/admin/commandes/'
    | '/admin/container/'
    | '/admin/devis/'
    | '/admin/produits/'
    | '/client/devis/'
    | '/admin/devis/generer/$reference'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ClientRoute: typeof ClientRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client': {
      id: '/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof ClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/': {
      id: '/client/'
      path: '/'
      fullPath: '/client/'
      preLoaderRoute: typeof ClientIndexRouteImport
      parentRoute: typeof ClientRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/client/orders': {
      id: '/client/orders'
      path: '/orders'
      fullPath: '/client/orders'
      preLoaderRoute: typeof ClientOrdersRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/new-order': {
      id: '/client/new-order'
      path: '/new-order'
      fullPath: '/client/new-order'
      preLoaderRoute: typeof ClientNewOrderRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/catalog': {
      id: '/client/catalog'
      path: '/catalog'
      fullPath: '/client/catalog'
      preLoaderRoute: typeof ClientCatalogRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/ask': {
      id: '/client/ask'
      path: '/ask'
      fullPath: '/client/ask'
      preLoaderRoute: typeof ClientAskRouteImport
      parentRoute: typeof ClientRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pricing': {
      id: '/admin/pricing'
      path: '/pricing'
      fullPath: '/admin/pricing'
      preLoaderRoute: typeof AdminPricingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/margins': {
      id: '/admin/margins'
      path: '/margins'
      fullPath: '/admin/margins'
      preLoaderRoute: typeof AdminMarginsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/knowledge': {
      id: '/admin/knowledge'
      path: '/knowledge'
      fullPath: '/admin/knowledge'
      preLoaderRoute: typeof AdminKnowledgeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/export': {
      id: '/admin/export'
      path: '/export'
      fullPath: '/admin/export'
      preLoaderRoute: typeof AdminExportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/copilot': {
      id: '/admin/copilot'
      path: '/copilot'
      fullPath: '/admin/copilot'
      preLoaderRoute: typeof AdminCopilotRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/container': {
      id: '/admin/container'
      path: '/container'
      fullPath: '/admin/container'
      preLoaderRoute: typeof AdminContainerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/agents': {
      id: '/admin/agents'
      path: '/agents'
      fullPath: '/admin/agents'
      preLoaderRoute: typeof AdminAgentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/client/devis/': {
      id: '/client/devis/'
      path: '/devis'
      fullPath: '/client/devis/'
      preLoaderRoute: typeof ClientDevisIndexRouteImport
      parentRoute: typeof ClientRoute
    }
    '/admin/produits/': {
      id: '/admin/produits/'
      path: '/produits'
      fullPath: '/admin/produits/'
      preLoaderRoute: typeof AdminProduitsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/devis/': {
      id: '/admin/devis/'
      path: '/devis'
      fullPath: '/admin/devis/'
      preLoaderRoute: typeof AdminDevisIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/container/': {
      id: '/admin/container/'
      path: '/'
      fullPath: '/admin/container/'
      preLoaderRoute: typeof AdminContainerIndexRouteImport
      parentRoute: typeof AdminContainerRoute
    }
    '/admin/commandes/': {
      id: '/admin/commandes/'
      path: '/commandes'
      fullPath: '/admin/commandes/'
      preLoaderRoute: typeof AdminCommandesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clients/': {
      id: '/admin/clients/'
      path: '/clients'
      fullPath: '/admin/clients/'
      preLoaderRoute: typeof AdminClientsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/agents/': {
      id: '/admin/agents/'
      path: '/'
      fullPath: '/admin/agents/'
      preLoaderRoute: typeof AdminAgentsIndexRouteImport
      parentRoute: typeof AdminAgentsRoute
    }
    '/client/devis/$quoteId': {
      id: '/client/devis/$quoteId'
      path: '/devis/$quoteId'
      fullPath: '/client/devis/$quoteId'
      preLoaderRoute: typeof ClientDevisQuoteIdRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/commandes/$reference': {
      id: '/client/commandes/$reference'
      path: '/commandes/$reference'
      fullPath: '/client/commandes/$reference'
      preLoaderRoute: typeof ClientCommandesReferenceRouteImport
      parentRoute: typeof ClientRoute
    }
    '/admin/produits/nouveau': {
      id: '/admin/produits/nouveau'
      path: '/produits/nouveau'
      fullPath: '/admin/produits/nouveau'
      preLoaderRoute: typeof AdminProduitsNouveauRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/produits/import': {
      id: '/admin/produits/import'
      path: '/produits/import'
      fullPath: '/admin/produits/import'
      preLoaderRoute: typeof AdminProduitsImportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/produits/$ref': {
      id: '/admin/produits/$ref'
      path: '/produits/$ref'
      fullPath: '/admin/produits/$ref'
      preLoaderRoute: typeof AdminProduitsRefRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pricing-workflow/$orderId': {
      id: '/admin/pricing-workflow/$orderId'
      path: '/pricing-workflow/$orderId'
      fullPath: '/admin/pricing-workflow/$orderId'
      preLoaderRoute: typeof AdminPricingWorkflowOrderIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/order-details/$orderId': {
      id: '/admin/order-details/$orderId'
      path: '/order-details/$orderId'
      fullPath: '/admin/order-details/$orderId'
      preLoaderRoute: typeof AdminOrderDetailsOrderIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/devis/$quoteId': {
      id: '/admin/devis/$quoteId'
      path: '/devis/$quoteId'
      fullPath: '/admin/devis/$quoteId'
      preLoaderRoute: typeof AdminDevisQuoteIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/container/$orderId': {
      id: '/admin/container/$orderId'
      path: '/$orderId'
      fullPath: '/admin/container/$orderId'
      preLoaderRoute: typeof AdminContainerOrderIdRouteImport
      parentRoute: typeof AdminContainerRoute
    }
    '/admin/commandes/$reference': {
      id: '/admin/commandes/$reference'
      path: '/commandes/$reference'
      fullPath: '/admin/commandes/$reference'
      preLoaderRoute: typeof AdminCommandesReferenceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clients/$clientId': {
      id: '/admin/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/admin/clients/$clientId'
      preLoaderRoute: typeof AdminClientsClientIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/agents/pricing': {
      id: '/admin/agents/pricing'
      path: '/pricing'
      fullPath: '/admin/agents/pricing'
      preLoaderRoute: typeof AdminAgentsPricingRouteImport
      parentRoute: typeof AdminAgentsRoute
    }
    '/admin/agents/marge': {
      id: '/admin/agents/marge'
      path: '/marge'
      fullPath: '/admin/agents/marge'
      preLoaderRoute: typeof AdminAgentsMargeRouteImport
      parentRoute: typeof AdminAgentsRoute
    }
    '/admin/agents/export': {
      id: '/admin/agents/export'
      path: '/export'
      fullPath: '/admin/agents/export'
      preLoaderRoute: typeof AdminAgentsExportRouteImport
      parentRoute: typeof AdminAgentsRoute
    }
    '/admin/agents/container-optimizer': {
      id: '/admin/agents/container-optimizer'
      path: '/container-optimizer'
      fullPath: '/admin/agents/container-optimizer'
      preLoaderRoute: typeof AdminAgentsContainerOptimizerRouteImport
      parentRoute: typeof AdminAgentsRoute
    }
    '/admin/agents/$agentId': {
      id: '/admin/agents/$agentId'
      path: '/$agentId'
      fullPath: '/admin/agents/$agentId'
      preLoaderRoute: typeof AdminAgentsAgentIdRouteImport
      parentRoute: typeof AdminAgentsRoute
    }
    '/admin/devis/generer/$reference': {
      id: '/admin/devis/generer/$reference'
      path: '/devis/generer/$reference'
      fullPath: '/admin/devis/generer/$reference'
      preLoaderRoute: typeof AdminDevisGenererReferenceRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminAgentsRouteChildren {
  AdminAgentsAgentIdRoute: typeof AdminAgentsAgentIdRoute
  AdminAgentsContainerOptimizerRoute: typeof AdminAgentsContainerOptimizerRoute
  AdminAgentsExportRoute: typeof AdminAgentsExportRoute
  AdminAgentsMargeRoute: typeof AdminAgentsMargeRoute
  AdminAgentsPricingRoute: typeof AdminAgentsPricingRoute
  AdminAgentsIndexRoute: typeof AdminAgentsIndexRoute
}

const AdminAgentsRouteChildren: AdminAgentsRouteChildren = {
  AdminAgentsAgentIdRoute: AdminAgentsAgentIdRoute,
  AdminAgentsContainerOptimizerRoute: AdminAgentsContainerOptimizerRoute,
  AdminAgentsExportRoute: AdminAgentsExportRoute,
  AdminAgentsMargeRoute: AdminAgentsMargeRoute,
  AdminAgentsPricingRoute: AdminAgentsPricingRoute,
  AdminAgentsIndexRoute: AdminAgentsIndexRoute,
}

const AdminAgentsRouteWithChildren = AdminAgentsRoute._addFileChildren(
  AdminAgentsRouteChildren,
)

interface AdminContainerRouteChildren {
  AdminContainerOrderIdRoute: typeof AdminContainerOrderIdRoute
  AdminContainerIndexRoute: typeof AdminContainerIndexRoute
}

const AdminContainerRouteChildren: AdminContainerRouteChildren = {
  AdminContainerOrderIdRoute: AdminContainerOrderIdRoute,
  AdminContainerIndexRoute: AdminContainerIndexRoute,
}

const AdminContainerRouteWithChildren = AdminContainerRoute._addFileChildren(
  AdminContainerRouteChildren,
)

interface AdminRouteChildren {
  AdminAgentsRoute: typeof AdminAgentsRouteWithChildren
  AdminContainerRoute: typeof AdminContainerRouteWithChildren
  AdminCopilotRoute: typeof AdminCopilotRoute
  AdminExportRoute: typeof AdminExportRoute
  AdminKnowledgeRoute: typeof AdminKnowledgeRoute
  AdminMarginsRoute: typeof AdminMarginsRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPricingRoute: typeof AdminPricingRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminClientsClientIdRoute: typeof AdminClientsClientIdRoute
  AdminCommandesReferenceRoute: typeof AdminCommandesReferenceRoute
  AdminDevisQuoteIdRoute: typeof AdminDevisQuoteIdRoute
  AdminOrderDetailsOrderIdRoute: typeof AdminOrderDetailsOrderIdRoute
  AdminPricingWorkflowOrderIdRoute: typeof AdminPricingWorkflowOrderIdRoute
  AdminProduitsRefRoute: typeof AdminProduitsRefRoute
  AdminProduitsImportRoute: typeof AdminProduitsImportRoute
  AdminProduitsNouveauRoute: typeof AdminProduitsNouveauRoute
  AdminClientsIndexRoute: typeof AdminClientsIndexRoute
  AdminCommandesIndexRoute: typeof AdminCommandesIndexRoute
  AdminDevisIndexRoute: typeof AdminDevisIndexRoute
  AdminProduitsIndexRoute: typeof AdminProduitsIndexRoute
  AdminDevisGenererReferenceRoute: typeof AdminDevisGenererReferenceRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAgentsRoute: AdminAgentsRouteWithChildren,
  AdminContainerRoute: AdminContainerRouteWithChildren,
  AdminCopilotRoute: AdminCopilotRoute,
  AdminExportRoute: AdminExportRoute,
  AdminKnowledgeRoute: AdminKnowledgeRoute,
  AdminMarginsRoute: AdminMarginsRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPricingRoute: AdminPricingRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminClientsClientIdRoute: AdminClientsClientIdRoute,
  AdminCommandesReferenceRoute: AdminCommandesReferenceRoute,
  AdminDevisQuoteIdRoute: AdminDevisQuoteIdRoute,
  AdminOrderDetailsOrderIdRoute: AdminOrderDetailsOrderIdRoute,
  AdminPricingWorkflowOrderIdRoute: AdminPricingWorkflowOrderIdRoute,
  AdminProduitsRefRoute: AdminProduitsRefRoute,
  AdminProduitsImportRoute: AdminProduitsImportRoute,
  AdminProduitsNouveauRoute: AdminProduitsNouveauRoute,
  AdminClientsIndexRoute: AdminClientsIndexRoute,
  AdminCommandesIndexRoute: AdminCommandesIndexRoute,
  AdminDevisIndexRoute: AdminDevisIndexRoute,
  AdminProduitsIndexRoute: AdminProduitsIndexRoute,
  AdminDevisGenererReferenceRoute: AdminDevisGenererReferenceRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ClientRouteChildren {
  ClientAskRoute: typeof ClientAskRoute
  ClientCatalogRoute: typeof ClientCatalogRoute
  ClientNewOrderRoute: typeof ClientNewOrderRoute
  ClientOrdersRoute: typeof ClientOrdersRoute
  ClientIndexRoute: typeof ClientIndexRoute
  ClientCommandesReferenceRoute: typeof ClientCommandesReferenceRoute
  ClientDevisQuoteIdRoute: typeof ClientDevisQuoteIdRoute
  ClientDevisIndexRoute: typeof ClientDevisIndexRoute
}

const ClientRouteChildren: ClientRouteChildren = {
  ClientAskRoute: ClientAskRoute,
  ClientCatalogRoute: ClientCatalogRoute,
  ClientNewOrderRoute: ClientNewOrderRoute,
  ClientOrdersRoute: ClientOrdersRoute,
  ClientIndexRoute: ClientIndexRoute,
  ClientCommandesReferenceRoute: ClientCommandesReferenceRoute,
  ClientDevisQuoteIdRoute: ClientDevisQuoteIdRoute,
  ClientDevisIndexRoute: ClientDevisIndexRoute,
}

const ClientRouteWithChildren =
  ClientRoute._addFileChildren(ClientRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ClientRoute: ClientRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
